// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import "forge-std/Test.sol";

/// @title Tests for the `Register` runtime bytecode
/// @notice The runtime bytecode is loaded from
///         `test/Register.bytecode.hex`, generated by
///         `lake exe register-dump-bytecode` from
///         `../Program.lean :: bytecode`.
///
///         The Lean proofs in `../Proofs.lean` establish:
///         - `program_result`: exact structural post-state.
///         - `program_updates_caller_account`: after the call the
///           contract's account has `acc.updateStorage sender x` for
///           the code owner.
///         - `program_preserves_other_accounts`: addresses other
///           than the code owner are untouched.
///
///         These Foundry tests exercise the same properties
///         end-to-end against a real `forge` EVM.
contract RegisterTest is Test {
    address constant REGISTER =
        address(0x0000000000000000000000000000000000001337);

    function setUp() public {
        string memory raw = vm.readFile("test/Register.bytecode.hex");
        bytes memory runtime = vm.parseBytes(_trim(raw));
        vm.etch(REGISTER, runtime);
    }

    // ------------- helpers -------------

    function _call(address sender, uint256 x) internal {
        vm.prank(sender);
        (bool ok, ) = REGISTER.call(abi.encodePacked(x));
        require(ok, "register call failed");
    }

    function _callEmpty(address sender) internal {
        vm.prank(sender);
        (bool ok, ) = REGISTER.call("");
        require(ok, "register call with empty calldata failed");
    }

    function _slot(address sender) internal view returns (uint256) {
        return uint256(vm.load(REGISTER, bytes32(uint256(uint160(sender)))));
    }

    /// @dev Strip trailing \n, \r, \t, space.
    function _trim(string memory s) internal pure returns (string memory) {
        bytes memory b = bytes(s);
        uint256 n = b.length;
        while (
            n > 0 &&
            (b[n - 1] == 0x0a || b[n - 1] == 0x0d ||
             b[n - 1] == 0x09 || b[n - 1] == 0x20)
        ) {
            n--;
        }
        bytes memory r = new bytes(n);
        for (uint256 i = 0; i < n; i++) r[i] = b[i];
        return string(r);
    }

    // ------------- concrete tests -------------

    function test_Register_writes_slot() public {
        _call(address(0xAA), 42);
        assertEq(_slot(address(0xAA)), 42);
    }

    function test_Register_isolates_senders() public {
        _call(address(0xAA), 111);
        _call(address(0xBB), 222);
        assertEq(_slot(address(0xAA)), 111);
        assertEq(_slot(address(0xBB)), 222);
    }

    function test_Register_overwrites() public {
        _call(address(0xAA), 1);
        assertEq(_slot(address(0xAA)), 1);
        _call(address(0xAA), 2);
        assertEq(_slot(address(0xAA)), 2);
    }

    function test_Register_empty_calldata_stores_zero() public {
        // CALLDATALOAD on empty calldata returns 0.
        _callEmpty(address(0xAA));
        assertEq(_slot(address(0xAA)), 0);
    }

    function test_Register_zero_value_clears_slot() public {
        _call(address(0xAA), 7);
        assertEq(_slot(address(0xAA)), 7);
        _call(address(0xAA), 0);
        assertEq(_slot(address(0xAA)), 0);
    }

    function test_Register_one_sender_does_not_touch_another() public {
        // Pre-populate 0xBB's slot by storing 99 (from 0xBB).
        _call(address(0xBB), 99);
        assertEq(_slot(address(0xBB)), 99);

        // Now 0xAA does a bunch of writes; 0xBB's slot must remain 99.
        _call(address(0xAA), 1);
        assertEq(_slot(address(0xBB)), 99);
        _call(address(0xAA), 2);
        assertEq(_slot(address(0xBB)), 99);
        _call(address(0xAA), 0);
        assertEq(_slot(address(0xBB)), 99);
    }

    // ------------- fuzz -------------

    function testFuzz_Register_writes(address sender, uint256 x) public {
        vm.assume(sender != address(0));  // vm.prank(0) is treated as deployment
        _call(sender, x);
        assertEq(_slot(sender), x);
    }

    function testFuzz_Register_isolates(
        address s1, uint256 x1,
        address s2, uint256 x2
    ) public {
        vm.assume(s1 != address(0));
        vm.assume(s2 != address(0));
        vm.assume(s1 != s2);
        _call(s1, x1);
        _call(s2, x2);
        assertEq(_slot(s1), x1);
        assertEq(_slot(s2), x2);
    }
}
