// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import "forge-std/Test.sol";
import {WethHandler} from "./WethHandler.sol";
import {WethReentrancyAttacker} from "./WethReentrancy.sol";

/// @title Tests for the `Weth` runtime bytecode
/// @notice Bytecode loaded from `test/Weth.bytecode.hex`, generated by
///         `lake exe weth-dump-bytecode` from
///         `../Program.lean :: bytecode`.
///
///         Covers: concrete deposit/withdraw flows, reentrancy,
///         fuzz correctness, and the main safety invariant
///         `Σ balances ≤ contract ETH balance` (weakened to ≤ to
///         tolerate force-fed ETH).
contract WethTest is Test {
    address constant WETH =
        address(uint160(0x5c00));

    WethHandler handler;

    function setUp() public {
        string memory raw = vm.readFile("test/Weth.bytecode.hex");
        bytes memory runtime = vm.parseBytes(_trim(raw));
        vm.etch(WETH, runtime);
        handler = new WethHandler(WETH);

        // For invariant tests only: target the handler.
        targetContract(address(handler));
    }

    // ------------- helpers -------------

    function _deposit(address sender, uint256 v) internal {
        vm.deal(sender, sender.balance + v);
        vm.prank(sender);
        (bool ok,) = WETH.call{value: v}(hex"d0e30db0");
        require(ok, "deposit failed");
    }

    function _withdraw(address sender, uint256 x) internal returns (bool ok) {
        vm.prank(sender);
        (ok,) = WETH.call(abi.encodeWithSelector(bytes4(0x2e1a7d4d), x));
    }

    function _bal(address a) internal view returns (uint256) {
        return uint256(vm.load(WETH, bytes32(uint256(uint160(a)))));
    }

    function _trim(string memory s) internal pure returns (string memory) {
        bytes memory b = bytes(s);
        uint256 n = b.length;
        while (n > 0 &&
               (b[n - 1] == 0x0a || b[n - 1] == 0x0d ||
                b[n - 1] == 0x09 || b[n - 1] == 0x20)) {
            n--;
        }
        bytes memory r = new bytes(n);
        for (uint256 i = 0; i < n; i++) r[i] = b[i];
        return string(r);
    }

    // ------------- concrete tests -------------

    function test_Weth_deposit_credits_sender() public {
        _deposit(address(0xAA), 1 ether);
        assertEq(_bal(address(0xAA)), 1 ether);
        assertEq(WETH.balance, 1 ether);
    }

    function test_Weth_deposit_accumulates() public {
        _deposit(address(0xAA), 1 ether);
        _deposit(address(0xAA), 2 ether);
        assertEq(_bal(address(0xAA)), 3 ether);
        assertEq(WETH.balance, 3 ether);
    }

    function test_Weth_withdraw_full() public {
        _deposit(address(0xAA), 5 ether);
        assertEq(address(0xAA).balance, 0);
        bool ok = _withdraw(address(0xAA), 5 ether);
        assertTrue(ok);
        assertEq(_bal(address(0xAA)), 0);
        assertEq(address(0xAA).balance, 5 ether);
        assertEq(WETH.balance, 0);
    }

    function test_Weth_withdraw_partial() public {
        _deposit(address(0xAA), 10 ether);
        bool ok = _withdraw(address(0xAA), 3 ether);
        assertTrue(ok);
        assertEq(_bal(address(0xAA)), 7 ether);
        assertEq(address(0xAA).balance, 3 ether);
        assertEq(WETH.balance, 7 ether);
    }

    function test_Weth_withdraw_insufficient_reverts() public {
        bool ok = _withdraw(address(0xAA), 1 ether);
        assertFalse(ok, "withdraw without deposit must fail");
        assertEq(_bal(address(0xAA)), 0);
    }

    function test_Weth_withdraw_exact_plus_one_reverts() public {
        _deposit(address(0xAA), 3 ether);
        bool ok = _withdraw(address(0xAA), 3 ether + 1);
        assertFalse(ok);
        // State must be unchanged (revert rolls back).
        assertEq(_bal(address(0xAA)), 3 ether);
        assertEq(WETH.balance, 3 ether);
    }

    function test_Weth_withdraw_zero_succeeds() public {
        bool ok = _withdraw(address(0xAA), 0);
        assertTrue(ok);
        assertEq(_bal(address(0xAA)), 0);
    }

    function test_Weth_senders_are_independent() public {
        _deposit(address(0xAA), 1 ether);
        _deposit(address(0xBB), 2 ether);
        assertEq(_bal(address(0xAA)), 1 ether);
        assertEq(_bal(address(0xBB)), 2 ether);
        _withdraw(address(0xAA), 1 ether);
        assertEq(_bal(address(0xAA)), 0);
        assertEq(_bal(address(0xBB)), 2 ether);   // unaffected
    }

    function test_Weth_bad_selector_reverts() public {
        vm.prank(address(0xAA));
        (bool ok,) = WETH.call(hex"deadbeef");
        assertFalse(ok);
    }

    function test_Weth_empty_calldata_reverts() public {
        vm.prank(address(0xAA));
        (bool ok,) = WETH.call("");
        assertFalse(ok);
    }

    // ------------- reentrancy -------------

    function test_Weth_reentrancy_does_not_drain() public {
        WethReentrancyAttacker atk = new WethReentrancyAttacker(WETH);
        // The test contract has ample ETH by default; fund the deposit
        // call directly via `{value: …}`, no vm.deal needed (and don't
        // double-fund by calling both).
        atk.deposit{value: 1 ether}();
        assertEq(_bal(address(atk)), 1 ether);
        assertEq(address(atk).balance, 0, "attacker holds no pre-existing ETH");

        // Attack: withdraw. The attacker's receive() will try to
        // reenter withdraw. The outer call succeeds (attacker gets
        // 1 ETH back), inner reentry silently fails (balance already
        // 0 via checks-effects-interactions), and WETH is NOT drained
        // beyond the legitimate 1 ETH.
        atk.attack(1 ether);

        // Post-conditions: invariant is that attacker got their
        // deposit back, nothing more.
        assertEq(_bal(address(atk)), 0, "token balance back to 0");
        assertEq(address(atk).balance, 1 ether, "attacker got exactly 1 ETH");
        assertEq(WETH.balance, 0, "contract drained by exactly 1 ETH");
        assertGe(atk.reentries(), 1, "reentry fired at least once");
    }

    // ------------- fuzz -------------

    function testFuzz_deposit_correct(uint96 v) public {
        vm.assume(v > 0);
        _deposit(address(0xAA), v);
        assertEq(_bal(address(0xAA)), v);
    }

    function testFuzz_withdraw_after_deposit(uint96 deposited, uint96 requested) public {
        vm.assume(deposited > 0);
        _deposit(address(0xAA), deposited);
        bool ok = _withdraw(address(0xAA), requested);
        if (requested <= deposited) {
            assertTrue(ok);
            assertEq(_bal(address(0xAA)), uint256(deposited) - uint256(requested));
        } else {
            assertFalse(ok);
            assertEq(_bal(address(0xAA)), deposited);
        }
    }

    // ------------- invariants (main safety claim) -------------

    /// Σ tracked-user balances ≤ contract ETH balance.
    function invariant_user_funds_never_lost() public view {
        uint256 sum;
        uint256 n = handler.actorCount();
        for (uint256 i = 0; i < n; i++) {
            sum += uint256(vm.load(WETH, bytes32(uint256(uint160(handler.actors(i))))));
        }
        assertLe(sum, WETH.balance);
    }

    /// Ghost accounting: contract ETH balance ≥ recorded deposits minus
    /// withdrawals. Weakened from equality (≥, not =) to tolerate
    /// force-fed ETH via SELFDESTRUCT or coinbase rewards.
    function invariant_ghost_accounting_consistent() public view {
        assertGe(
            WETH.balance,
            handler.ghostTotalDeposited() - handler.ghostTotalWithdrawn()
        );
    }
}
