// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import "forge-std/Test.sol";

/// @title Tests for the `add3` runtime bytecode
/// @notice The runtime bytecode is loaded from `test/Add3.bytecode.hex`,
///         generated by `lake exe add3-dump-bytecode` from
///         `../Program.lean :: bytecode`. The arithmetic correctness of
///         the compute prefix is proved in `../Proofs.lean` as
///         `compute_correct`.
contract Add3Test is Test {
    address constant ADD3 =
        address(0x000000000000000000000000000000000000add3);

    function setUp() public {
        string memory raw = vm.readFile("test/Add3.bytecode.hex");
        bytes memory runtime = vm.parseBytes(_trim(raw));
        vm.etch(ADD3, runtime);
    }

    // ------------- helpers -------------

    function _callAdd3(uint256 a, uint256 b, uint256 c)
        internal
        returns (uint256)
    {
        bytes memory cd = abi.encodePacked(a, b, c);
        (bool ok, bytes memory ret) = ADD3.call(cd);
        require(ok, "add3 call failed");
        assertEq(ret.length, 32, "return size");
        return abi.decode(ret, (uint256));
    }

    function _callRaw(bytes memory cd) internal returns (bytes memory ret) {
        bool ok;
        (ok, ret) = ADD3.call(cd);
        require(ok, "call failed");
    }

    /// @dev Strip trailing \n, \r (Windows CRLF), \t, space.
    function _trim(string memory s) internal pure returns (string memory) {
        bytes memory b = bytes(s);
        uint256 n = b.length;
        while (
            n > 0 &&
            (b[n - 1] == 0x0a || b[n - 1] == 0x0d ||
             b[n - 1] == 0x09 || b[n - 1] == 0x20)
        ) {
            n--;
        }
        bytes memory r = new bytes(n);
        for (uint256 i = 0; i < n; i++) r[i] = b[i];
        return string(r);
    }

    // ------------- concrete tests -------------

    function test_Add3_concrete() public {
        assertEq(_callAdd3(1, 2, 3), 6);
        assertEq(_callAdd3(10, 20, 30), 60);
        assertEq(_callAdd3(0, 0, 0), 0);
    }

    function test_Add3_wraps() public {
        assertEq(_callAdd3(type(uint256).max, 1, 0), 0);
        unchecked {
            uint256 expected =
                type(uint256).max + type(uint256).max + type(uint256).max;
            assertEq(
                _callAdd3(type(uint256).max, type(uint256).max, type(uint256).max),
                expected
            );
        }
    }

    function test_Add3_shortCalldata() public {
        // Empty calldata → all three CALLDATALOAD reads return 0.
        (bool ok, bytes memory ret) = ADD3.call("");
        require(ok, "empty calldata should not revert");
        assertEq(abi.decode(ret, (uint256)), 0);

        // 32 bytes → b and c zero-padded to 0.
        ret = _callRaw(abi.encodePacked(uint256(5)));
        assertEq(abi.decode(ret, (uint256)), 5);

        // 64 bytes → c zero-padded to 0.
        ret = _callRaw(abi.encodePacked(uint256(5), uint256(7)));
        assertEq(abi.decode(ret, (uint256)), 12);
    }

    function test_Add3_longCalldata() public {
        // 128 bytes: fourth word ignored.
        bytes memory cd = abi.encodePacked(
            uint256(1), uint256(2), uint256(3), uint256(999)
        );
        (bool ok, bytes memory ret) = ADD3.call(cd);
        require(ok);
        assertEq(abi.decode(ret, (uint256)), 6);
    }

    // ------------- fuzz -------------

    function testFuzz_Add3(uint256 a, uint256 b, uint256 c) public {
        unchecked {
            uint256 expected = a + b + c;
            assertEq(_callAdd3(a, b, c), expected);
        }
    }
}
