// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import "forge-std/Test.sol";

/// @title Tests for the `Groth16` runtime bytecode
/// @notice Bytecode loaded from `test/Groth16.bytecode.hex`, generated by
///         `lake exe groth16-dump-bytecode` from `../Program.lean :: bytecode`.
///
///         The proof/public-input constants below are real: produced by
///         `circuit/square.circom` (`y = x*x`, `x = 3`, `y = 9`) through an
///         actual `circom` + `snarkjs` Groth16 setup/prove, with the same
///         verifying key baked into `Program.lean`'s constants. See
///         `../circuit/` to regenerate. This is the end-to-end check that
///         the hand-assembled bytecode — calldata decoding, memory layout,
///         the three precompile calls — actually agrees with a real proof,
///         on a real EVM (Foundry's revm), independent of Lean.
contract Groth16Test is Test {
    address constant VERIFIER = address(uint160(0x6701));

    // proof for x = 3, y = 9 (circuit/proof.json + circuit/public.json,
    // reordered into calldata order via `snarkjs generatecall`).
    uint256 constant Ax  = 0x1436394a7a720743fd709443ec3bddee84b5d15af72f7b30de99429458466987;
    uint256 constant Ay  = 0x145fd6737532999f6f7e54238225c1edfd97893e98ffe3ece5569da53573709f;
    uint256 constant Bx1 = 0x0000201a8505badf54f5f17a02eff349ea1d225aabc09eae27a3f3fcabe3b4fe;
    uint256 constant Bx0 = 0x2dc9aa285aeff75b29eb74e000546f235d9c10cd493006470fa990fba592eba7;
    uint256 constant By1 = 0x2aa9b607e9fbf7ce7d26c48d7910fd123d00e91a91edc2a1282f8e0bab0392ed;
    uint256 constant By0 = 0x00a5d72782da85a80edb669cb34dd0471f175ef4f2016502c33873f366efeba4;
    uint256 constant Cx  = 0x14de0c4e98c6abfefabd35e18f31e60d6f8477b2317817b5db49495928f4ffef;
    uint256 constant Cy  = 0x1c2eec5c65a2bbd28d9d83c46c50effa12e3e56ca243935c72341375b2e53685;
    uint256 constant INPUT = 9;

    // BN254 scalar-field modulus (the order of the curve's prime subgroup,
    // `Fr` -- not `q`, the base field `Fq` the curve coordinates live in).
    uint256 constant R = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function setUp() public {
        string memory raw = vm.readFile("test/Groth16.bytecode.hex");
        bytes memory runtime = vm.parseBytes(_trim(raw));
        vm.etch(VERIFIER, runtime);
    }

    // ------------- helpers -------------

    function _verify(uint256 ax, uint256 ay, uint256 bx1, uint256 bx0, uint256 by1, uint256 by0,
        uint256 cx, uint256 cy, uint256 input) internal returns (bool ok, bytes memory ret) {
        bytes memory calldata_ = abi.encodePacked(
            bytes4(0x43753b4d), ax, ay, bx1, bx0, by1, by0, cx, cy, input
        );
        (ok, ret) = VERIFIER.call(calldata_);
    }

    function _trim(string memory s) internal pure returns (string memory) {
        bytes memory b = bytes(s);
        uint256 n = b.length;
        while (n > 0 &&
               (b[n - 1] == 0x0a || b[n - 1] == 0x0d ||
                b[n - 1] == 0x09 || b[n - 1] == 0x20)) {
            n--;
        }
        bytes memory r = new bytes(n);
        for (uint256 i = 0; i < n; i++) r[i] = b[i];
        return string(r);
    }

    // ------------- tests -------------

    /// The real proof, against the real public input it was generated for,
    /// must verify: the contract must return `true`.
    function test_Groth16_real_proof_verifies() public {
        (bool ok, bytes memory ret) = _verify(Ax, Ay, Bx1, Bx0, By1, By0, Cx, Cy, INPUT);
        assertTrue(ok, "call must not revert");
        assertEq(ret.length, 32);
        assertEq(abi.decode(ret, (uint256)), 1, "must verify true");
    }

    /// The same proof against the wrong public input (10, not 9) must
    /// verify false — the pairing check fails, but the call itself does
    /// not revert (matches the reference verifier's behaviour).
    function test_Groth16_wrong_public_input_fails() public {
        (bool ok, bytes memory ret) = _verify(Ax, Ay, Bx1, Bx0, By1, By0, Cx, Cy, INPUT + 1);
        assertTrue(ok, "call must not revert");
        assertEq(abi.decode(ret, (uint256)), 0, "must verify false");
    }

    /// A wrong-but-valid `C` (the `alt_bn128` generator `(1, 2)`, standing
    /// in for the real `proof.C`) must verify false. (Note: an *off-curve*
    /// corruption like `C.x + 1` instead makes `ECPAIRING` itself revert,
    /// per EIP-197 — correct precompile behaviour, not a bug here; this
    /// test picks a corruption that stays on-curve so the failure shows up
    /// as `false`, not a revert.)
    function test_Groth16_wrong_proof_point_fails() public {
        (bool ok, bytes memory ret) = _verify(Ax, Ay, Bx1, Bx0, By1, By0, 1, 2, INPUT);
        assertTrue(ok, "call must not revert");
        assertEq(abi.decode(ret, (uint256)), 0, "must verify false");
    }

    /// An off-curve proof point (`C.x + 1`) makes the underlying
    /// `ECPAIRING` precompile itself revert (EIP-197) — and so must this
    /// contract, which relays the precompile's success bit.
    function test_Groth16_off_curve_point_reverts() public {
        (bool ok,) = _verify(Ax, Ay, Bx1, Bx0, By1, By0, Cx + 1, Cy, INPUT);
        assertFalse(ok, "off-curve point must revert");
    }

    /// An unknown selector reverts (no fallback).
    function test_Groth16_bad_selector_reverts() public {
        (bool ok,) = VERIFIER.call(hex"deadbeef");
        assertFalse(ok);
    }

    /// `checkField`: a non-canonical public input (`INPUT + r`) must revert,
    /// even though -- absent the guard -- it would verify identically to
    /// `INPUT`. `EC_MUL` multiplies by a point of order `r`, so
    /// `(INPUT + r)*P = INPUT*P`: the pairing check itself cannot tell the
    /// two inputs apart. Without `checkField`, a caller could submit
    /// `INPUT + r` and have it verify true, while a downstream consumer
    /// reading the raw `uint256` calldata value sees a different number
    /// than the canonical `INPUT`. This is the scenario `checkField` exists
    /// to rule out.
    function test_Groth16_non_canonical_input_reverts() public {
        (bool ok,) = _verify(Ax, Ay, Bx1, Bx0, By1, By0, Cx, Cy, INPUT + R);
        assertFalse(ok, "non-canonical input (input + r) must revert");
    }
}
